function celltxt = CreateLegend( nFreq, freq, leg_ang, maxGain, maxGindx, minGain, minGindx )
%NSICREATELEGEND Summary of this function goes here
%   Detailed explanation goes here


for i=1:nFreq
    tmptxt = [ 
            num2str(ceil(freq(i)/(1*10^6))), ' MHz : ' , ...
            ];
     celltxt(i,:)=cellstr(tmptxt);
end

%             ' G = (', ...
%                 num2str(maxGain(1,1,i)),'@',num2str(leg_ang(maxGindx(1,1,i))) '^o',' | ', ...
%                 num2str(minGain(1,1,i)),'@',num2str(leg_ang(minGindx(1,1,i))) '^o) dBi' ...


%            ' Gain(max|min) = (', ...
%                num2str(maxGain(1,1,i)),'@',num2str(leg_ang(maxGindx(1,1,i))) '^o',' | ', ...
%                num2str(minGain(1,1,i)),'@',num2str(leg_ang(minGindx(1,1,i))) '^o)' ...
