function [freq NumAxis NumLayers phi_parm theta_parm DataUnFMT_FULL filename pathname, Date] = satDataRead(satDataPath)


[filename, pathname] = uigetfile('*.trx*', 'Pick a .trx2 file generated by Satimo chamber S/W ');
if isequal(filename,0)|isequal(pathname,0)
   disp('File not found')
else
   disp(['File ', pathname, filename, ' found'])
end
fid=fopen([pathname filename], 'r');
filelabel=strrep(filename,'.trx2','');

fHandle = dir([pathname filename]);
Date = fHandle.date;

filetype=fgets(fid);
NumAxis=str2num(fgets(fid));
NumLayers=str2num(fgets(fid));

Axis0Name=fgets(fid);  %axis 0 *should* be Frequency
fparmcell=textscan(fid, '%f', 'commentStyle', '!', 'MultipleDelimsAsOne',1);
f_parm=cell2mat(fparmcell);
f_parm=double(f_parm);
Axis0Dist=textscan(fid, '%[LISTOGN]'); % checks for Distribution types of "LIST", "LOG", or "LIN"

if isequal(deblank(char(Axis0Dist{:})),'LIST')
    Axis0Listcell=textscan(fid, '%f');
    freq=cell2mat(Axis0Listcell);
else
    freq=linspace(f_parm(3), f_parm(4), f_parm(2)).'; 
end


Axis1Name=fgets(fid);  %axis 1 *should* be Phi
phiparmcell=textscan(fid, '%f', 'commentStyle', '!', 'MultipleDelimsAsOne',1);
phi_parm=cell2mat(phiparmcell);
Axis1Dist=textscan(fid, '%[LIN ]'); % checks for Distribution types of "LIST", "LOG", or "LIN"

Axis2Name=fgets(fid);  %axis 2 *should* be Theta
thetaparmcell=textscan(fid, '%f', 'commentStyle', '!', 'MultipleDelimsAsOne',1);
theta_parm=cell2mat(thetaparmcell);
Axis2Dist=textscan(fid, '%[LIN ]'); % checks for Distribution types of "LIST", "LOG", or "LIN"

for k=1:NumLayers

LayerNameCellArr{k}=fgets(fid);  %cell array containing layer names
LayerNames=cell2mat(LayerNameCellArr);
LayerUnitsCellArr{k}=fgets(fid); %cell array containing layer units
LayerUnits=cell2mat(LayerUnitsCellArr); %0=Linear Units, 13=dB,
end

DataCellArray=textscan(fid, '%f%f%f%f%f%f%f','delimiter','/t','MultipleDelimsAsOne',1,'CollectOutput',1);
DataUnFMT_FULL=cell2mat(DataCellArray);





    